# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en

class PartnershipDisguisedSaleInput:
    def __init__(self, asset_basis: Money, asset_fair_market_value: Money, cash_distributed_to_transferor: Money, debt_financed_distribution: Money, transferor_allocable_liability: Money, tax_rate: Decimal) -> None:
        self.asset_basis = asset_basis
        self.asset_fair_market_value = asset_fair_market_value
        self.cash_distributed_to_transferor = cash_distributed_to_transferor
        self.debt_financed_distribution = debt_financed_distribution
        self.transferor_allocable_liability = transferor_allocable_liability
        self.tax_rate = tax_rate

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PartnershipDisguisedSaleInput):
            return (self.asset_basis == other.asset_basis and self.asset_fair_market_value == other.asset_fair_market_value and self.cash_distributed_to_transferor == other.cash_distributed_to_transferor and self.debt_financed_distribution == other.debt_financed_distribution and self.transferor_allocable_liability == other.transferor_allocable_liability and self.tax_rate == other.tax_rate)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PartnershipDisguisedSaleInput(asset_basis={},asset_fair_market_value={},cash_distributed_to_transferor={},debt_financed_distribution={},transferor_allocable_liability={},tax_rate={})".format(self.asset_basis, self.asset_fair_market_value, self.cash_distributed_to_transferor, self.debt_financed_distribution, self.transferor_allocable_liability, self.tax_rate)

class PartnershipDisguisedSaleComputation:
    def __init__(self, tax_savings: Money, recognized_gain_output: Money, baseline_gain_output: Money, deferred_gain_output: Money) -> None:
        self.tax_savings = tax_savings
        self.recognized_gain_output = recognized_gain_output
        self.baseline_gain_output = baseline_gain_output
        self.deferred_gain_output = deferred_gain_output

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PartnershipDisguisedSaleComputation):
            return (self.tax_savings == other.tax_savings and self.recognized_gain_output == other.recognized_gain_output and self.baseline_gain_output == other.baseline_gain_output and self.deferred_gain_output == other.deferred_gain_output)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PartnershipDisguisedSaleComputation(tax_savings={},recognized_gain_output={},baseline_gain_output={},deferred_gain_output={})".format(self.tax_savings, self.recognized_gain_output, self.baseline_gain_output, self.deferred_gain_output)

class TestTribunePattern:
    def __init__(self, computation: PartnershipDisguisedSaleComputation) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestTribunePattern):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestTribunePattern(computation={})".format(self.computation)

class PartnershipDisguisedSaleComputationIn:
    def __init__(self, transaction_in: PartnershipDisguisedSaleInput) -> None:
        self.transaction_in = transaction_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, PartnershipDisguisedSaleComputationIn):
            return (self.transaction_in == other.transaction_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "PartnershipDisguisedSaleComputationIn(transaction_in={})".format(self.transaction_in)

class TestTribunePatternIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestTribunePatternIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestTribunePatternIn()".format()


def partnership_disguised_sale_computation(partnership_disguised_sale_computation_in:PartnershipDisguisedSaleComputationIn):
    transaction = (partnership_disguised_sale_computation_in.transaction_in)
    if (transaction.debt_financed_distribution <= transaction.transferor_allocable_liability):
        liability_excluded_distribution = (transaction.debt_financed_distribution)
    else:
        liability_excluded_distribution = (transaction.transferor_allocable_liability)
    if (transaction.asset_fair_market_value <= transaction.asset_basis):
        baseline_gain = (Money(Integer(0)))
    else:
        baseline_gain = ((transaction.asset_fair_market_value - transaction.asset_basis))
    if (transaction.cash_distributed_to_transferor <= liability_excluded_distribution):
        amount_taken_into_account = (Money(Integer(0)))
    else:
        amount_taken_into_account = ((transaction.cash_distributed_to_transferor - liability_excluded_distribution))
    baseline_gain_output = (baseline_gain)
    baseline_tax_due = ((baseline_gain * transaction.tax_rate))
    if (amount_taken_into_account <= transaction.asset_basis):
        recognized_gain = (Money(Integer(0)))
    else:
        recognized_gain = ((amount_taken_into_account - transaction.asset_basis))
    recognized_gain_output = (recognized_gain)
    actual_tax_due = ((recognized_gain * transaction.tax_rate))
    if (baseline_gain <= recognized_gain):
        deferred_gain = (Money(Integer(0)))
    else:
        deferred_gain = ((baseline_gain - recognized_gain))
    tax_savings = ((baseline_tax_due - actual_tax_due))
    deferred_gain_output = (deferred_gain)
    return PartnershipDisguisedSaleComputation(tax_savings = tax_savings, recognized_gain_output = recognized_gain_output, baseline_gain_output = baseline_gain_output, deferred_gain_output = deferred_gain_output)

def test_tribune_pattern(test_tribune_pattern_in:TestTribunePatternIn):
    result = (partnership_disguised_sale_computation(PartnershipDisguisedSaleComputationIn(transaction_in = PartnershipDisguisedSaleInput(asset_basis = Money(Integer(0)), asset_fair_market_value = Money(Integer(10000)), cash_distributed_to_transferor = Money(Integer(10000)), debt_financed_distribution = Money(Integer(9000)), transferor_allocable_liability = Money(Integer(9000)), tax_rate = decimal_of_string("1/5")))))
    computation = (PartnershipDisguisedSaleComputation(tax_savings = result.tax_savings, recognized_gain_output = result.recognized_gain_output, baseline_gain_output = result.baseline_gain_output, deferred_gain_output = result.deferred_gain_output))
    return TestTribunePattern(computation = computation)
