# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en

class PaymentKind_Code(Enum):
    Royalty = 0
    Dividend = 1
    ServiceFee = 2

class PaymentKind:
    def __init__(self, code: PaymentKind_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, PaymentKind):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)

class Jurisdiction_Code(Enum):
    Ireland = 0
    Bermuda = 1
    Netherlands = 2
    US = 3
    Germany = 4

class Jurisdiction:
    def __init__(self, code: Jurisdiction_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, Jurisdiction):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)

class CorporateTaxComputation:
    def __init__(self, tax_due: Money) -> None:
        self.tax_due = tax_due

    def __eq__(self, other: object) -> bool:
        if isinstance(other, CorporateTaxComputation):
            return (self.tax_due == other.tax_due)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "CorporateTaxComputation(tax_due={})".format(self.tax_due)

class WithholdingTaxComputation:
    def __init__(self, withholding_tax_due: Money) -> None:
        self.withholding_tax_due = withholding_tax_due

    def __eq__(self, other: object) -> bool:
        if isinstance(other, WithholdingTaxComputation):
            return (self.withholding_tax_due == other.withholding_tax_due)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "WithholdingTaxComputation(withholding_tax_due={})".format(self.withholding_tax_due)

class EntityTaxOutcome:
    def __init__(self, total_tax: Money) -> None:
        self.total_tax = total_tax

    def __eq__(self, other: object) -> bool:
        if isinstance(other, EntityTaxOutcome):
            return (self.total_tax == other.total_tax)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "EntityTaxOutcome(total_tax={})".format(self.total_tax)

class GroupTaxOutcome:
    def __init__(self, total_group_tax: Money) -> None:
        self.total_group_tax = total_group_tax

    def __eq__(self, other: object) -> bool:
        if isinstance(other, GroupTaxOutcome):
            return (self.total_group_tax == other.total_group_tax)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "GroupTaxOutcome(total_group_tax={})".format(self.total_group_tax)

class Entity:
    def __init__(self, incorporation_jurisdiction: Jurisdiction, tax_residence: Jurisdiction) -> None:
        self.incorporation_jurisdiction = incorporation_jurisdiction
        self.tax_residence = tax_residence

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Entity):
            return (self.incorporation_jurisdiction == other.incorporation_jurisdiction and self.tax_residence == other.tax_residence)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "Entity(incorporation_jurisdiction={},tax_residence={})".format(self.incorporation_jurisdiction, self.tax_residence)

class TestCorporateTaxComputation:
    def __init__(self, computation: CorporateTaxComputation) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestCorporateTaxComputation):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestCorporateTaxComputation(computation={})".format(self.computation)

class TestWithholding:
    def __init__(self, computation: WithholdingTaxComputation) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestWithholding):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestWithholding(computation={})".format(self.computation)

class TestEntityTaxOutcome:
    def __init__(self, computation: EntityTaxOutcome) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestEntityTaxOutcome):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestEntityTaxOutcome(computation={})".format(self.computation)

class Payment:
    def __init__(self, payer: Entity, receiver: Entity, amount: Money, kind: PaymentKind) -> None:
        self.payer = payer
        self.receiver = receiver
        self.amount = amount
        self.kind = kind

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Payment):
            return (self.payer == other.payer and self.receiver == other.receiver and self.amount == other.amount and self.kind == other.kind)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "Payment(payer={},receiver={},amount={},kind={})".format(self.payer, self.receiver, self.amount, self.kind)

class EntityTaxInput:
    def __init__(self, entity: Entity, gross_revenue: Money, outgoing_payments: List[Payment]) -> None:
        self.entity = entity
        self.gross_revenue = gross_revenue
        self.outgoing_payments = outgoing_payments

    def __eq__(self, other: object) -> bool:
        if isinstance(other, EntityTaxInput):
            return (self.entity == other.entity and self.gross_revenue == other.gross_revenue and self.outgoing_payments == other.outgoing_payments)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "EntityTaxInput(entity={},gross_revenue={},outgoing_payments={})".format(self.entity, self.gross_revenue, self.outgoing_payments)

class CorporateTaxComputationIn:
    def __init__(self, entity_in: Entity, gross_revenue_in: Money, outgoing_payments_in: List[Payment]) -> None:
        self.entity_in = entity_in
        self.gross_revenue_in = gross_revenue_in
        self.outgoing_payments_in = outgoing_payments_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, CorporateTaxComputationIn):
            return (self.entity_in == other.entity_in and self.gross_revenue_in == other.gross_revenue_in and self.outgoing_payments_in == other.outgoing_payments_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "CorporateTaxComputationIn(entity_in={},gross_revenue_in={},outgoing_payments_in={})".format(self.entity_in, self.gross_revenue_in, self.outgoing_payments_in)

class WithholdingTaxComputationIn:
    def __init__(self, payment_in: Payment) -> None:
        self.payment_in = payment_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, WithholdingTaxComputationIn):
            return (self.payment_in == other.payment_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "WithholdingTaxComputationIn(payment_in={})".format(self.payment_in)

class EntityTaxOutcomeIn:
    def __init__(self, entity_in: Entity, gross_revenue_in: Money, outgoing_payments_in: List[Payment]) -> None:
        self.entity_in = entity_in
        self.gross_revenue_in = gross_revenue_in
        self.outgoing_payments_in = outgoing_payments_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, EntityTaxOutcomeIn):
            return (self.entity_in == other.entity_in and self.gross_revenue_in == other.gross_revenue_in and self.outgoing_payments_in == other.outgoing_payments_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "EntityTaxOutcomeIn(entity_in={},gross_revenue_in={},outgoing_payments_in={})".format(self.entity_in, self.gross_revenue_in, self.outgoing_payments_in)

class GroupTaxOutcomeIn:
    def __init__(self, entity_inputs_in: List[EntityTaxInput]) -> None:
        self.entity_inputs_in = entity_inputs_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, GroupTaxOutcomeIn):
            return (self.entity_inputs_in == other.entity_inputs_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "GroupTaxOutcomeIn(entity_inputs_in={})".format(self.entity_inputs_in)

class TestCorporateTaxComputationIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestCorporateTaxComputationIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestCorporateTaxComputationIn()".format()

class TestWithholdingIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestWithholdingIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestWithholdingIn()".format()

class TestEntityTaxOutcomeIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestEntityTaxOutcomeIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestEntityTaxOutcomeIn()".format()


def corporate_tax_computation(corporate_tax_computation_in:CorporateTaxComputationIn):
    entity = (corporate_tax_computation_in.entity_in)
    gross_revenue = (corporate_tax_computation_in.gross_revenue_in)
    outgoing_payments = (corporate_tax_computation_in.outgoing_payments_in)
    tax_rate__1 = (entity.tax_residence)
    if tax_rate__1.code == Jurisdiction_Code.Ireland:
        tax_rate = (decimal_of_string("1/8"))
    elif tax_rate__1.code == Jurisdiction_Code.Bermuda:
        tax_rate = (decimal_of_string("0"))
    elif tax_rate__1.code == Jurisdiction_Code.Netherlands:
        tax_rate = (decimal_of_string("129/500"))
    elif tax_rate__1.code == Jurisdiction_Code.US:
        tax_rate = (decimal_of_string("21/100"))
    elif tax_rate__1.code == Jurisdiction_Code.Germany:
        tax_rate = (decimal_of_string("3/20"))
    def deductible_payments__1(payment:Payment):
        deductible_payments__3 = (payment.kind)
        if deductible_payments__3.code == PaymentKind_Code.Royalty:
            deductible_payments__2 = (True)
        elif deductible_payments__3.code == PaymentKind_Code.Dividend:
            deductible_payments__2 = (False)
        elif deductible_payments__3.code == PaymentKind_Code.ServiceFee:
            deductible_payments__2 = (False)
        if deductible_payments__2:
            return payment.amount
        else:
            return Money(Integer(0))
    deductible_payments = (money_en.sum(list_map(deductible_payments__1, outgoing_payments)))
    if ((gross_revenue - deductible_payments) <= Money(Integer(0))):
        tax_base = (Money(Integer(0)))
    else:
        tax_base = ((gross_revenue - deductible_payments))
    tax_due = ((tax_base * tax_rate))
    return CorporateTaxComputation(tax_due = tax_due)

def withholding_tax_computation(withholding_tax_computation_in:WithholdingTaxComputationIn):
    payment = (withholding_tax_computation_in.payment_in)
    withholding_rate__2 = (payment.kind)
    if withholding_rate__2.code == PaymentKind_Code.Royalty:
        withholding_rate__1 = (True)
    elif withholding_rate__2.code == PaymentKind_Code.Dividend:
        withholding_rate__1 = (False)
    elif withholding_rate__2.code == PaymentKind_Code.ServiceFee:
        withholding_rate__1 = (False)
    if withholding_rate__1:
        if (payment.payer.tax_residence == Jurisdiction(Jurisdiction_Code.Ireland, Unit())):
            if (payment.receiver.tax_residence == Jurisdiction(Jurisdiction_Code.Netherlands, Unit())):
                withholding_rate = (decimal_of_string("0"))
            elif (payment.receiver.tax_residence == Jurisdiction(Jurisdiction_Code.Bermuda, Unit())):
                withholding_rate = (decimal_of_string("1/5"))
            else:
                withholding_rate = (decimal_of_string("1/10"))
        elif (payment.payer.tax_residence == Jurisdiction(Jurisdiction_Code.Netherlands, Unit())):
            if (payment.receiver.tax_residence == Jurisdiction(Jurisdiction_Code.Bermuda, Unit())):
                withholding_rate = (decimal_of_string("0"))
            else:
                withholding_rate = (decimal_of_string("1/20"))
        elif (payment.payer.tax_residence == Jurisdiction(Jurisdiction_Code.Bermuda, Unit())):
            withholding_rate = (decimal_of_string("0"))
        elif (payment.payer.tax_residence == Jurisdiction(Jurisdiction_Code.US, Unit())):
            withholding_rate = (decimal_of_string("1/10"))
        else:
            withholding_rate = (decimal_of_string("3/20"))
    else:
        withholding_rate = (decimal_of_string("0"))
    withholding_tax_due = ((payment.amount * withholding_rate))
    return WithholdingTaxComputation(withholding_tax_due = withholding_tax_due)

def test_corporate_tax_computation(test_corporate_tax_computation_in:TestCorporateTaxComputationIn):
    result = (corporate_tax_computation(CorporateTaxComputationIn(entity_in = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Ireland, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Ireland, Unit())), gross_revenue_in = Money(Integer(10000)), outgoing_payments_in = [Payment(payer = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Netherlands, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Netherlands, Unit())), receiver = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Netherlands, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Netherlands, Unit())), amount = Money(Integer(9000)), kind = PaymentKind(PaymentKind_Code.Royalty, Unit()))])))
    computation = (CorporateTaxComputation(tax_due = result.tax_due))
    return TestCorporateTaxComputation(computation = computation)

def test_withholding(test_withholding_in:TestWithholdingIn):
    result = (withholding_tax_computation(WithholdingTaxComputationIn(payment_in = Payment(payer = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Ireland, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Ireland, Unit())), receiver = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Netherlands, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Netherlands, Unit())), amount = Money(Integer(9000)), kind = PaymentKind(PaymentKind_Code.Royalty, Unit())))))
    computation = (WithholdingTaxComputation(withholding_tax_due = result.withholding_tax_due))
    return TestWithholding(computation = computation)

def entity_tax_outcome(entity_tax_outcome_in:EntityTaxOutcomeIn):
    entity = (entity_tax_outcome_in.entity_in)
    gross_revenue = (entity_tax_outcome_in.gross_revenue_in)
    outgoing_payments = (entity_tax_outcome_in.outgoing_payments_in)
    def withholding_tax__1(payment:Payment):
        result = (withholding_tax_computation(WithholdingTaxComputationIn(payment_in = payment)))
        return WithholdingTaxComputation(withholding_tax_due = result.withholding_tax_due).withholding_tax_due
    withholding_tax = (money_en.sum(list_map(withholding_tax__1, outgoing_payments)))
    result__1 = (corporate_tax_computation(CorporateTaxComputationIn(entity_in = entity, gross_revenue_in = gross_revenue, outgoing_payments_in = outgoing_payments)))
    corporate_tax_computation__1 = (CorporateTaxComputation(tax_due = result__1.tax_due))
    total_tax = ((corporate_tax_computation__1.tax_due + withholding_tax))
    return EntityTaxOutcome(total_tax = total_tax)

def test_entity_tax_outcome(test_entity_tax_outcome_in:TestEntityTaxOutcomeIn):
    result = (entity_tax_outcome(EntityTaxOutcomeIn(entity_in = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Ireland, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Ireland, Unit())), gross_revenue_in = Money(Integer(10000)), outgoing_payments_in = [Payment(payer = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Ireland, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Ireland, Unit())), receiver = Entity(incorporation_jurisdiction = Jurisdiction(Jurisdiction_Code.Netherlands, Unit()), tax_residence = Jurisdiction(Jurisdiction_Code.Netherlands, Unit())), amount = Money(Integer(9000)), kind = PaymentKind(PaymentKind_Code.Royalty, Unit()))])))
    computation = (EntityTaxOutcome(total_tax = result.total_tax))
    return TestEntityTaxOutcome(computation = computation)

def group_tax_outcome(group_tax_outcome_in:GroupTaxOutcomeIn):
    entity_inputs = (group_tax_outcome_in.entity_inputs_in)
    def total_group_tax__1(entity_input:EntityTaxInput):
        result = (entity_tax_outcome(EntityTaxOutcomeIn(entity_in = entity_input.entity, gross_revenue_in = entity_input.gross_revenue, outgoing_payments_in = entity_input.outgoing_payments)))
        return EntityTaxOutcome(total_tax = result.total_tax).total_tax
    total_group_tax = (money_en.sum(list_map(total_group_tax__1, entity_inputs)))
    return GroupTaxOutcome(total_group_tax = total_group_tax)
