# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en

class RecognizedStraddleHistory:
    def __init__(self, gain_leg_realized: bool, loss_leg_realized: bool) -> None:
        self.gain_leg_realized = gain_leg_realized
        self.loss_leg_realized = loss_leg_realized

    def __eq__(self, other: object) -> bool:
        if isinstance(other, RecognizedStraddleHistory):
            return (self.gain_leg_realized == other.gain_leg_realized and self.loss_leg_realized == other.loss_leg_realized)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "RecognizedStraddleHistory(gain_leg_realized={},loss_leg_realized={})".format(self.gain_leg_realized, self.loss_leg_realized)

class TaxpayerCtfAllocation:
    def __init__(self, allocated_gain: Money, allocated_loss: Money, tax_rate: Decimal) -> None:
        self.allocated_gain = allocated_gain
        self.allocated_loss = allocated_loss
        self.tax_rate = tax_rate

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaxpayerCtfAllocation):
            return (self.allocated_gain == other.allocated_gain and self.allocated_loss == other.allocated_loss and self.tax_rate == other.tax_rate)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TaxpayerCtfAllocation(allocated_gain={},allocated_loss={},tax_rate={})".format(self.allocated_gain, self.allocated_loss, self.tax_rate)

class TaxpayerStraddleTaxComputation:
    def __init__(self, after_tax_income: Money) -> None:
        self.after_tax_income = after_tax_income

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaxpayerStraddleTaxComputation):
            return (self.after_tax_income == other.after_tax_income)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TaxpayerStraddleTaxComputation(after_tax_income={})".format(self.after_tax_income)

class CommonTrustFundTaxInput:
    def __init__(self, straddle_history: RecognizedStraddleHistory, taxpayer_allocation: TaxpayerCtfAllocation) -> None:
        self.straddle_history = straddle_history
        self.taxpayer_allocation = taxpayer_allocation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, CommonTrustFundTaxInput):
            return (self.straddle_history == other.straddle_history and self.taxpayer_allocation == other.taxpayer_allocation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "CommonTrustFundTaxInput(straddle_history={},taxpayer_allocation={})".format(self.straddle_history, self.taxpayer_allocation)

class TestGainAndLossOffset:
    def __init__(self, computation: TaxpayerStraddleTaxComputation) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestGainAndLossOffset):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestGainAndLossOffset(computation={})".format(self.computation)

class TestGainOnly:
    def __init__(self, computation: TaxpayerStraddleTaxComputation) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestGainOnly):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestGainOnly(computation={})".format(self.computation)

class TestNoRealizedGain:
    def __init__(self, computation: TaxpayerStraddleTaxComputation) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestNoRealizedGain):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestNoRealizedGain(computation={})".format(self.computation)

class TaxpayerStraddleTaxComputationIn:
    def __init__(self, ctf_tax_input_in: CommonTrustFundTaxInput) -> None:
        self.ctf_tax_input_in = ctf_tax_input_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaxpayerStraddleTaxComputationIn):
            return (self.ctf_tax_input_in == other.ctf_tax_input_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TaxpayerStraddleTaxComputationIn(ctf_tax_input_in={})".format(self.ctf_tax_input_in)

class TestNoRealizedGainIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestNoRealizedGainIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestNoRealizedGainIn()".format()

class TestGainOnlyIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestGainOnlyIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestGainOnlyIn()".format()

class TestGainAndLossOffsetIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestGainAndLossOffsetIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestGainAndLossOffsetIn()".format()


def taxpayer_straddle_tax_computation(taxpayer_straddle_tax_computation_in:TaxpayerStraddleTaxComputationIn):
    ctf_tax_input = (taxpayer_straddle_tax_computation_in.ctf_tax_input_in)
    if ctf_tax_input.straddle_history.loss_leg_realized:
        realized_loss = (ctf_tax_input.taxpayer_allocation.allocated_loss)
    else:
        realized_loss = (Money(Integer(0)))
    if ctf_tax_input.straddle_history.gain_leg_realized:
        realized_gain = (ctf_tax_input.taxpayer_allocation.allocated_gain)
    else:
        realized_gain = (Money(Integer(0)))
    taxable_income = ((realized_gain - realized_loss))
    if (taxable_income <= Money(Integer(0))):
        tax_due = (Money(Integer(0)))
    else:
        tax_due = ((taxable_income * ctf_tax_input.taxpayer_allocation.tax_rate))
    after_tax_income = ((taxable_income - tax_due))
    return TaxpayerStraddleTaxComputation(after_tax_income = after_tax_income)

def test_gain_and_loss_offset(test_gain_and_loss_offset_in:TestGainAndLossOffsetIn):
    result = (taxpayer_straddle_tax_computation(TaxpayerStraddleTaxComputationIn(ctf_tax_input_in = CommonTrustFundTaxInput(straddle_history = RecognizedStraddleHistory(gain_leg_realized = True, loss_leg_realized = True), taxpayer_allocation = TaxpayerCtfAllocation(allocated_gain = Money(Integer(10000)), allocated_loss = Money(Integer(6000)), tax_rate = decimal_of_string("37/100"))))))
    computation = (TaxpayerStraddleTaxComputation(after_tax_income = result.after_tax_income))
    return TestGainAndLossOffset(computation = computation)

def test_gain_only(test_gain_only_in:TestGainOnlyIn):
    result = (taxpayer_straddle_tax_computation(TaxpayerStraddleTaxComputationIn(ctf_tax_input_in = CommonTrustFundTaxInput(straddle_history = RecognizedStraddleHistory(gain_leg_realized = True, loss_leg_realized = False), taxpayer_allocation = TaxpayerCtfAllocation(allocated_gain = Money(Integer(10000)), allocated_loss = Money(Integer(0)), tax_rate = decimal_of_string("37/100"))))))
    computation = (TaxpayerStraddleTaxComputation(after_tax_income = result.after_tax_income))
    return TestGainOnly(computation = computation)

def test_no_realized_gain(test_no_realized_gain_in:TestNoRealizedGainIn):
    result = (taxpayer_straddle_tax_computation(TaxpayerStraddleTaxComputationIn(ctf_tax_input_in = CommonTrustFundTaxInput(straddle_history = RecognizedStraddleHistory(gain_leg_realized = False, loss_leg_realized = False), taxpayer_allocation = TaxpayerCtfAllocation(allocated_gain = Money(Integer(10000)), allocated_loss = Money(Integer(0)), tax_rate = decimal_of_string("37/100"))))))
    computation = (TaxpayerStraddleTaxComputation(after_tax_income = result.after_tax_income))
    return TestNoRealizedGain(computation = computation)
