# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en

class TaxResidence_Code(Enum):
    US = 0
    Foreign = 1

class TaxResidence:
    def __init__(self, code: TaxResidence_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, TaxResidence):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)

class Asset:
    def __init__(self, basis: Money, fair_market_value: Money, sale_price: Money) -> None:
        self.basis = basis
        self.fair_market_value = fair_market_value
        self.sale_price = sale_price

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Asset):
            return (self.basis == other.basis and self.fair_market_value == other.fair_market_value and self.sale_price == other.sale_price)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "Asset(basis={},fair_market_value={},sale_price={})".format(self.basis, self.fair_market_value, self.sale_price)

class DistressedAssetTrustComputation:
    def __init__(self, would_be_tax_savings: Money) -> None:
        self.would_be_tax_savings = would_be_tax_savings

    def __eq__(self, other: object) -> bool:
        if isinstance(other, DistressedAssetTrustComputation):
            return (self.would_be_tax_savings == other.would_be_tax_savings)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "DistressedAssetTrustComputation(would_be_tax_savings={})".format(self.would_be_tax_savings)

class Individual:
    def __init__(self, tax_residence: TaxResidence) -> None:
        self.tax_residence = tax_residence

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Individual):
            return (self.tax_residence == other.tax_residence)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "Individual(tax_residence={})".format(self.tax_residence)

class TrustArrangement:
    def __init__(self, taxpayer: Individual, transferor: Individual, asset: Asset, taxpayer_has_section_678_power: bool, taxpayer_bore_economic_loss: bool) -> None:
        self.taxpayer = taxpayer
        self.transferor = transferor
        self.asset = asset
        self.taxpayer_has_section_678_power = taxpayer_has_section_678_power
        self.taxpayer_bore_economic_loss = taxpayer_bore_economic_loss

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TrustArrangement):
            return (self.taxpayer == other.taxpayer and self.transferor == other.transferor and self.asset == other.asset and self.taxpayer_has_section_678_power == other.taxpayer_has_section_678_power and self.taxpayer_bore_economic_loss == other.taxpayer_bore_economic_loss)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TrustArrangement(taxpayer={},transferor={},asset={},taxpayer_has_section_678_power={},taxpayer_bore_economic_loss={})".format(self.taxpayer, self.transferor, self.asset, self.taxpayer_has_section_678_power, self.taxpayer_bore_economic_loss)

class DistressedAssetTrustComputationIn:
    def __init__(self, arrangement_in: TrustArrangement, tax_rate_in: Decimal) -> None:
        self.arrangement_in = arrangement_in
        self.tax_rate_in = tax_rate_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, DistressedAssetTrustComputationIn):
            return (self.arrangement_in == other.arrangement_in and self.tax_rate_in == other.tax_rate_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "DistressedAssetTrustComputationIn(arrangement_in={},tax_rate_in={})".format(self.arrangement_in, self.tax_rate_in)


def distressed_asset_trust_computation(distressed_asset_trust_computation_in:DistressedAssetTrustComputationIn):
    arrangement = (distressed_asset_trust_computation_in.arrangement_in)
    tax_rate = (distressed_asset_trust_computation_in.tax_rate_in)
    realized_loss = ((arrangement.asset.basis - arrangement.asset.sale_price))
    if arrangement.taxpayer_has_section_678_power:
        claimed_loss = (realized_loss)
    else:
        claimed_loss = (Money(Integer(0)))
    would_be_tax_savings = ((claimed_loss * tax_rate))
    return DistressedAssetTrustComputation(would_be_tax_savings = would_be_tax_savings)
