[project]
include_dirs = ["formalizations/"]
build_dir = "formalizations/_build"
target_dir = "formalizations/_target"

[[target]]
name = "distressed_tax_rules"
modules = ["DistressedAssetTaxModel"]
backends = ["python"]