# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en

class BarnesGroupTaxComputation:
    def __init__(self, section_956_inclusion: Money, tax_due: Money) -> None:
        self.section_956_inclusion = section_956_inclusion
        self.tax_due = tax_due

    def __eq__(self, other: object) -> bool:
        if isinstance(other, BarnesGroupTaxComputation):
            return (self.section_956_inclusion == other.section_956_inclusion and self.tax_due == other.tax_due)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "BarnesGroupTaxComputation(section_956_inclusion={},tax_due={})".format(self.section_956_inclusion, self.tax_due)

class BarnesGroupTaxComputationIn:
    def __init__(self, domestic_stock_basis_in: Money, applicable_earnings_in: Money, tax_rate_in: Decimal) -> None:
        self.domestic_stock_basis_in = domestic_stock_basis_in
        self.applicable_earnings_in = applicable_earnings_in
        self.tax_rate_in = tax_rate_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, BarnesGroupTaxComputationIn):
            return (self.domestic_stock_basis_in == other.domestic_stock_basis_in and self.applicable_earnings_in == other.applicable_earnings_in and self.tax_rate_in == other.tax_rate_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "BarnesGroupTaxComputationIn(domestic_stock_basis_in={},applicable_earnings_in={},tax_rate_in={})".format(self.domestic_stock_basis_in, self.applicable_earnings_in, self.tax_rate_in)


def barnes_group_tax_computation(barnes_group_tax_computation_in:BarnesGroupTaxComputationIn):
    domestic_stock_basis = (barnes_group_tax_computation_in.domestic_stock_basis_in)
    applicable_earnings = (barnes_group_tax_computation_in.applicable_earnings_in)
    tax_rate = (barnes_group_tax_computation_in.tax_rate_in)
    if (domestic_stock_basis < applicable_earnings):
        section_956_inclusion = (domestic_stock_basis)
    else:
        section_956_inclusion = (applicable_earnings)
    tax_due = ((section_956_inclusion * tax_rate))
    return BarnesGroupTaxComputation(section_956_inclusion = section_956_inclusion, tax_due = tax_due)
