# This file has been generated by the Catala compiler, do not edit!

from catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Stdlib_en as stdlib_en
from . import Date_en as date_en
from . import List_en as list_en
from . import Duration_en as duration_en
from . import MonthYear_en as month_year_en
from . import Period_en as period_en
from . import Money_en as money_en
from . import Integer_en as integer_en
from . import Decimal_en as decimal_en

class StockCompLiquidationInput:
    def __init__(self, stock_compensation_fair_market_value: Money, shareholder_stock_basis: Money, liquidation_distribution_fair_market_value: Money, shareholder_ownership_percent: Decimal) -> None:
        self.stock_compensation_fair_market_value = stock_compensation_fair_market_value
        self.shareholder_stock_basis = shareholder_stock_basis
        self.liquidation_distribution_fair_market_value = liquidation_distribution_fair_market_value
        self.shareholder_ownership_percent = shareholder_ownership_percent

    def __eq__(self, other: object) -> bool:
        if isinstance(other, StockCompLiquidationInput):
            return (self.stock_compensation_fair_market_value == other.stock_compensation_fair_market_value and self.shareholder_stock_basis == other.shareholder_stock_basis and self.liquidation_distribution_fair_market_value == other.liquidation_distribution_fair_market_value and self.shareholder_ownership_percent == other.shareholder_ownership_percent)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "StockCompLiquidationInput(stock_compensation_fair_market_value={},shareholder_stock_basis={},liquidation_distribution_fair_market_value={},shareholder_ownership_percent={})".format(self.stock_compensation_fair_market_value, self.shareholder_stock_basis, self.liquidation_distribution_fair_market_value, self.shareholder_ownership_percent)

class SubsidiaryStockCompComputation:
    def __init__(self, ordinary_deduction: Money, capital_loss: Money, total_tax_advantage: Money) -> None:
        self.ordinary_deduction = ordinary_deduction
        self.capital_loss = capital_loss
        self.total_tax_advantage = total_tax_advantage

    def __eq__(self, other: object) -> bool:
        if isinstance(other, SubsidiaryStockCompComputation):
            return (self.ordinary_deduction == other.ordinary_deduction and self.capital_loss == other.capital_loss and self.total_tax_advantage == other.total_tax_advantage)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "SubsidiaryStockCompComputation(ordinary_deduction={},capital_loss={},total_tax_advantage={})".format(self.ordinary_deduction, self.capital_loss, self.total_tax_advantage)

class TestNotice200060Pattern:
    def __init__(self, computation: SubsidiaryStockCompComputation) -> None:
        self.computation = computation

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestNotice200060Pattern):
            return (self.computation == other.computation)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestNotice200060Pattern(computation={})".format(self.computation)

class SubsidiaryStockCompComputationIn:
    def __init__(self, transaction_in: StockCompLiquidationInput) -> None:
        self.transaction_in = transaction_in

    def __eq__(self, other: object) -> bool:
        if isinstance(other, SubsidiaryStockCompComputationIn):
            return (self.transaction_in == other.transaction_in)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "SubsidiaryStockCompComputationIn(transaction_in={})".format(self.transaction_in)

class TestNotice200060PatternIn:
    def __init__(self, ) -> None:
        pass

    def __eq__(self, other: object) -> bool:
        if isinstance(other, TestNotice200060PatternIn):
            return (True)
        else:
            return False

    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "TestNotice200060PatternIn()".format()


def subsidiary_stock_comp_computation(subsidiary_stock_comp_computation_in:SubsidiaryStockCompComputationIn):
    transaction = (subsidiary_stock_comp_computation_in.transaction_in)
    ordinary_deduction = (transaction.stock_compensation_fair_market_value)
    if (transaction.shareholder_stock_basis <= transaction.liquidation_distribution_fair_market_value):
        liquidation_loss = (Money(Integer(0)))
    else:
        liquidation_loss = ((transaction.shareholder_stock_basis - transaction.liquidation_distribution_fair_market_value))
    section_331_applies = ((transaction.shareholder_ownership_percent < decimal_of_string("4/5")))
    if section_331_applies:
        capital_loss = (liquidation_loss)
    else:
        capital_loss = (Money(Integer(0)))
    total_tax_advantage = ((ordinary_deduction + capital_loss))
    return SubsidiaryStockCompComputation(ordinary_deduction = ordinary_deduction, capital_loss = capital_loss, total_tax_advantage = total_tax_advantage)

def test_notice2000_60_pattern(test_notice2000_60_pattern_in:TestNotice200060PatternIn):
    result = (subsidiary_stock_comp_computation(SubsidiaryStockCompComputationIn(transaction_in = StockCompLiquidationInput(stock_compensation_fair_market_value = Money(Integer(9900)), shareholder_stock_basis = Money(Integer(10000)), liquidation_distribution_fair_market_value = Money(Integer(100)), shareholder_ownership_percent = decimal_of_string("1/2")))))
    computation = (SubsidiaryStockCompComputation(ordinary_deduction = result.ordinary_deduction, capital_loss = result.capital_loss, total_tax_advantage = result.total_tax_advantage))
    return TestNotice200060Pattern(computation = computation)
