(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Stdlib_en" "CM0|15e33851|32e49b03|165aeded"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Stdlib_en, it may need recompiling"
module Stdlib_en = Stdlib_en
let () =
  match Catala_runtime.check_module "Date_en" "CM0|15e33851|32e49b03|1be0e012"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_en, it may need recompiling"
module Date_en = Date_en
let () =
  match Catala_runtime.check_module "List_en" "CM0|15e33851|32e49b03|24a3fb7d"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_en, it may need recompiling"
module List_en = List_en
let () =
  match Catala_runtime.check_module "Duration_en" "CM0|15e33851|32e49b03|150e2ea0"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Duration_en, it may need recompiling"
module Duration_en = Duration_en
let () =
  match Catala_runtime.check_module "MonthYear_en" "CM0|15e33851|32e49b03|3436d8e8"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module MonthYear_en, it may need recompiling"
module MonthYear_en = MonthYear_en
let () =
  match Catala_runtime.check_module "Period_en" "CM0|15e33851|32e49b03|16c825d2"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Period_en, it may need recompiling"
module Period_en = Period_en
let () =
  match Catala_runtime.check_module "Money_en" "CM0|15e33851|32e49b03|22cf526d"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Money_en, it may need recompiling"
module Money_en = Money_en
let () =
  match Catala_runtime.check_module "Integer_en" "CM0|15e33851|32e49b03|1a7e2f37"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Integer_en, it may need recompiling"
module Integer_en = Integer_en
let () =
  match Catala_runtime.check_module "Decimal_en" "CM0|15e33851|32e49b03|2ee7fc57"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Decimal_en, it may need recompiling"
module Decimal_en = Decimal_en

module PaymentKind = struct type t = Royalty | Dividend | ServiceFee end

module Jurisdiction = struct
  type t = Ireland | Bermuda | Netherlands | US | France
end

module CorporateTaxComputation = struct
  type t = {tax_due: money}
end

module WithholdingTaxComputation = struct
  type t = {withholding_tax_due: money}
end

module EntityTaxOutcome = struct
  type t = {total_tax: money}
end

module GroupTaxOutcome = struct
  type t = {total_group_tax: money}
end

module Entity = struct
  type t = {
    incorporation_jurisdiction: Jurisdiction.t;
    tax_residence: Jurisdiction.t
  }
end

module TestCorporateTaxComputation = struct
  type t = {computation: CorporateTaxComputation.t}
end

module TestWithholding = struct
  type t = {computation: WithholdingTaxComputation.t}
end

module TestEntityTaxOutcome = struct
  type t = {computation: EntityTaxOutcome.t}
end

module Payment = struct
  type t = {
    payer: Entity.t;
    receiver: Entity.t;
    amount: money;
    kind: PaymentKind.t
  }
end

module EntityTaxInput = struct
  type t = {
    entity: Entity.t;
    gross_revenue: money;
    outgoing_payments: Payment.t array
  }
end

module CorporateTaxComputation_in = struct
  type t = {
    entity_in: Entity.t;
    gross_revenue_in: money;
    outgoing_payments_in: Payment.t array
  }
end

module WithholdingTaxComputation_in = struct
  type t = {payment_in: Payment.t}
end

module EntityTaxOutcome_in = struct
  type t = {
    entity_in: Entity.t;
    gross_revenue_in: money;
    outgoing_payments_in: Payment.t array
  }
end

module GroupTaxOutcome_in = struct
  type t = {entity_inputs_in: EntityTaxInput.t array}
end

module TestCorporateTaxComputation_in = struct
  type t = unit
end

module TestWithholding_in = struct
  type t = unit
end

module TestEntityTaxOutcome_in = struct
  type t = unit
end


(* Scope CorporateTaxComputation *)
let corporate_tax_computation :
  CorporateTaxComputation_in.t -> CorporateTaxComputation.t =
  fun corporate_tax_computation_in ->
  let entity: Entity.t =
    corporate_tax_computation_in.CorporateTaxComputation_in.entity_in in
  let gross_revenue: money =
    corporate_tax_computation_in.CorporateTaxComputation_in.gross_revenue_in in
  let outgoing_payments: Payment.t array =
    corporate_tax_computation_in.CorporateTaxComputation_in.outgoing_payments_in
    in
  let tax_rate: decimal =
    match (entity.Entity.tax_residence)
    with
    | Jurisdiction.Ireland -> (decimal_of_string "1/8")
    | Jurisdiction.Bermuda -> (decimal_of_string "0")
    | Jurisdiction.Netherlands -> (decimal_of_string "129/500")
    | Jurisdiction.US -> (decimal_of_string "21/100")
    | Jurisdiction.France -> (decimal_of_string "1/4") in
  let deductible_payments: money =
    (Money_en.sum)
      (o_map
         (fun (payment: Payment.t) ->
             if
              (match (payment.Payment.kind)
               with
               | PaymentKind.Royalty -> true
               | PaymentKind.Dividend -> false
               | PaymentKind.ServiceFee -> false) then
              (payment.Payment.amount) else
              (money_of_cents_string "0")) outgoing_payments) in
  let tax_base: money =
     if
      (o_lte_mon_mon
         (o_sub_mon_mon gross_revenue deductible_payments)
         (money_of_cents_string "0")) then
      (money_of_cents_string "0") else
      (o_sub_mon_mon gross_revenue deductible_payments) in
  let tax_due: money = o_mult_mon_rat tax_base tax_rate in
  {CorporateTaxComputation.tax_due = tax_due}

(* Scope WithholdingTaxComputation *)
let withholding_tax_computation :
  WithholdingTaxComputation_in.t -> WithholdingTaxComputation.t =
  fun withholding_tax_computation_in ->
  let payment: Payment.t =
    withholding_tax_computation_in.WithholdingTaxComputation_in.payment_in in
  let withholding_rate: decimal =
     if
      (match (payment.Payment.kind)
       with
       | PaymentKind.Royalty -> true
       | PaymentKind.Dividend -> false
       | PaymentKind.ServiceFee -> false) then
      ( if
         (o_eq ((payment.Payment.payer).Entity.tax_residence)
            (Jurisdiction.Ireland)) then
         ( if
            (o_eq ((payment.Payment.receiver).Entity.tax_residence)
               (Jurisdiction.Netherlands)) then
            (decimal_of_string "0") else
            ( if
               (o_eq
                  ((payment.Payment.receiver).Entity.tax_residence)
                  (Jurisdiction.Bermuda)) then
               (decimal_of_string "1/5") else
               (decimal_of_string "1/10"))) else
         ( if
            (o_eq ((payment.Payment.payer).Entity.tax_residence)
               (Jurisdiction.Netherlands)) then
            ( if
               (o_eq
                  ((payment.Payment.receiver).Entity.tax_residence)
                  (Jurisdiction.Bermuda)) then
               (decimal_of_string "0") else
               (decimal_of_string "1/20")) else
            ( if
               (o_eq ((payment.Payment.payer).Entity.tax_residence)
                  (Jurisdiction.Bermuda)) then
               (decimal_of_string "0") else
               ( if
                  (o_eq
                     ((payment.Payment.payer).Entity.tax_residence)
                     (Jurisdiction.US)) then
                  (decimal_of_string "1/10") else
                  (decimal_of_string "3/20"))))) else
      (decimal_of_string "0") in
  let withholding_tax_due: money =
    o_mult_mon_rat (payment.Payment.amount) withholding_rate in
  {WithholdingTaxComputation.withholding_tax_due =
     withholding_tax_due}

(* Scope TestCorporateTaxComputation *)
let _ :
  TestCorporateTaxComputation_in.t -> TestCorporateTaxComputation.t =
  fun _ ->
  let computation: CorporateTaxComputation.t =
    (let result : CorporateTaxComputation.t =
       (corporate_tax_computation
          ({CorporateTaxComputation_in.entity_in =
              ({Entity.incorporation_jurisdiction =
                  (Jurisdiction.Ireland);
                  Entity.tax_residence = (Jurisdiction.Ireland)});
              CorporateTaxComputation_in.gross_revenue_in =
                (money_of_cents_string "10000");
              CorporateTaxComputation_in.outgoing_payments_in =
                ([|({Payment.payer =
                       ({Entity.incorporation_jurisdiction =
                           (Jurisdiction.Netherlands);
                           Entity.tax_residence =
                             (Jurisdiction.Netherlands)});
                       Payment.receiver =
                         ({Entity.incorporation_jurisdiction =
                             (Jurisdiction.Netherlands);
                             Entity.tax_residence =
                               (Jurisdiction.Netherlands)});
                       Payment.amount = (money_of_cents_string
                         "9000");
                       Payment.kind = (PaymentKind.Royalty)})|])}))
    in
    ({CorporateTaxComputation.tax_due =
        (result.CorporateTaxComputation.tax_due)})) in
  {TestCorporateTaxComputation.computation = computation}

(* Scope TestWithholding *)
let _ : TestWithholding_in.t -> TestWithholding.t = fun _ ->
  let computation: WithholdingTaxComputation.t =
    (let result : WithholdingTaxComputation.t =
       (withholding_tax_computation
          ({WithholdingTaxComputation_in.payment_in =
              ({Payment.payer =
                  ({Entity.incorporation_jurisdiction =
                      (Jurisdiction.Ireland);
                      Entity.tax_residence = (Jurisdiction.Ireland)});
                  Payment.receiver =
                    ({Entity.incorporation_jurisdiction =
                        (Jurisdiction.Netherlands);
                        Entity.tax_residence =
                          (Jurisdiction.Netherlands)});
                  Payment.amount = (money_of_cents_string "9000");
                  Payment.kind = (PaymentKind.Royalty)})}))
    in
    ({WithholdingTaxComputation.withholding_tax_due =
        (result.WithholdingTaxComputation.withholding_tax_due)})) in
  {TestWithholding.computation = computation}

(* Scope EntityTaxOutcome *)
let entity_tax_outcome :
  EntityTaxOutcome_in.t -> EntityTaxOutcome.t =
  fun entity_tax_outcome_in ->
  let entity: Entity.t =
    entity_tax_outcome_in.EntityTaxOutcome_in.entity_in in
  let gross_revenue: money =
    entity_tax_outcome_in.EntityTaxOutcome_in.gross_revenue_in in
  let outgoing_payments: Payment.t array =
    entity_tax_outcome_in.EntityTaxOutcome_in.outgoing_payments_in in
  let withholding_tax: money =
    (Money_en.sum)
      (o_map
         (fun (payment: Payment.t) ->
            (let result : WithholdingTaxComputation.t =
               (withholding_tax_computation
                  ({WithholdingTaxComputation_in.payment_in = payment}))
            in
            ({WithholdingTaxComputation.withholding_tax_due =
                (result.WithholdingTaxComputation.withholding_tax_due)})).WithholdingTaxComputation.withholding_tax_due)
         outgoing_payments) in
  let corporate_tax_computation__1: CorporateTaxComputation.t =
    (let result : CorporateTaxComputation.t =
       (corporate_tax_computation
          ({CorporateTaxComputation_in.entity_in = entity;
              CorporateTaxComputation_in.gross_revenue_in =
                gross_revenue;
              CorporateTaxComputation_in.outgoing_payments_in =
                outgoing_payments}))
    in
    ({CorporateTaxComputation.tax_due =
        (result.CorporateTaxComputation.tax_due)})) in
  let total_tax: money =
    o_add_mon_mon
      (corporate_tax_computation__1.CorporateTaxComputation.tax_due)
      withholding_tax in
  {EntityTaxOutcome.total_tax = total_tax}

(* Scope TestEntityTaxOutcome *)
let _ : TestEntityTaxOutcome_in.t -> TestEntityTaxOutcome.t =
  fun _ ->
  let computation: EntityTaxOutcome.t =
    (let result : EntityTaxOutcome.t =
       (entity_tax_outcome
          ({EntityTaxOutcome_in.entity_in =
              ({Entity.incorporation_jurisdiction =
                  (Jurisdiction.Ireland);
                  Entity.tax_residence = (Jurisdiction.Ireland)});
              EntityTaxOutcome_in.gross_revenue_in =
                (money_of_cents_string "10000");
              EntityTaxOutcome_in.outgoing_payments_in =
                ([|({Payment.payer =
                       ({Entity.incorporation_jurisdiction =
                           (Jurisdiction.Ireland);
                           Entity.tax_residence =
                             (Jurisdiction.Ireland)});
                       Payment.receiver =
                         ({Entity.incorporation_jurisdiction =
                             (Jurisdiction.Netherlands);
                             Entity.tax_residence =
                               (Jurisdiction.Netherlands)});
                       Payment.amount = (money_of_cents_string
                         "9000");
                       Payment.kind = (PaymentKind.Royalty)})|])}))
    in
    ({EntityTaxOutcome.total_tax =
        (result.EntityTaxOutcome.total_tax)})) in
  {TestEntityTaxOutcome.computation = computation}

(* Scope GroupTaxOutcome *)
let _ : GroupTaxOutcome_in.t -> GroupTaxOutcome.t =
  fun group_tax_outcome_in ->
  let entity_inputs: EntityTaxInput.t array =
    group_tax_outcome_in.GroupTaxOutcome_in.entity_inputs_in in
  let total_group_tax: money =
    (Money_en.sum)
      (o_map
         (fun (entity_input: EntityTaxInput.t) ->
            (let result : EntityTaxOutcome.t =
               (entity_tax_outcome
                  ({EntityTaxOutcome_in.entity_in =
                      (entity_input.EntityTaxInput.entity);
                      EntityTaxOutcome_in.gross_revenue_in =
                        (entity_input.EntityTaxInput.gross_revenue);
                      EntityTaxOutcome_in.outgoing_payments_in =
                        (entity_input.EntityTaxInput.outgoing_payments)}))
            in
            ({EntityTaxOutcome.total_tax =
                (result.EntityTaxOutcome.total_tax)})).EntityTaxOutcome.total_tax)
         entity_inputs) in
  {GroupTaxOutcome.total_group_tax = total_group_tax}

let () =
  Catala_runtime.register_module "TaxModel"
    [  ]
    "CM0|15e33851|32e49b03|26b8dd6a"
