[project]
include_dirs = ["formalizations/"]
build_dir = "formalizations/_build"
target_dir = "formalizations/_target"

[[target]]
name = "barnes_group_tax_rules"
modules = ["BarnesGroupTaxModel"]
backends = ["python"]
